name: CI - Build and test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
      - uses: actions/checkout@v3

      - name: setup nodejs
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: install dependencies
      - run: npm ci

      - name: run lint
      - run: npm run lint

      - name: run build
      - run: npm run build
